version: '3'

services:
  nginx:
    image: nginx:1.19
    volumes:  
      - /etc/ssl:/etc/ssl
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/ubuntu/kokorofoods2.0/backend/static
      - media_volume:/home/ubuntu/kokorofoods2.0/backend/media
      
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./front-end/kokorofoods
    volumes:
      - /root/.npm:/root/.npm

  backend:
    build:
      context: ./backend
    volumes:
      - /root/.cache/pip:/root/.cache/pip
      - static_volume:/home/ubuntu/kokorofoods2.0/backend/static
      - media_volume:/home/ubuntu/kokorofoods2.0/backend/media

    environment:
      - DB_HOST=db
      - DB_NAME=kokorofoods
      - DB_USER=titan
      - DB_PASS=titan09
    expose:
    - "8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kokorofoods
      - POSTGRES_USER=titan
      - POSTGRES_PASSWORD=titan09
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
  celery:
    restart: always
    build:
      context: ./backend
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=db
      - DB_NAME=kokorofoods
      - DB_USER=titan
      - DB_PASS=titan09
    depends_on:
      - db
      - redis
      - backend
  celery-beat:
    restart: always
    build:
      context: ./backend
    command: celery -A backend beat -l INFO
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=db
      - DB_NAME=kokorofoods
      - DB_USER=titan
      - DB_PASS=titan09
    depends_on:
      - db
      - redis
      - backend
volumes:
  static_volume:
  pgdata:
  media_volume:
