# Generated by Django 3.2.3 on 2021-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210531_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tradegecko_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
