# Generated by Django 3.2.4 on 2021-06-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_class_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
