# Generated by Django 3.2.4 on 2021-06-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210626_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shipping'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
