# Generated by Django 3.2.4 on 2021-06-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payku_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payku_verification_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
