# Generated by Django 3.2.4 on 2021-06-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210628_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
