# Generated by Django 3.2.4 on 2021-07-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210706_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boleta_pdf',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='folio_sii',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='lioren_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
