# Generated by Django 3.2.5 on 2021-07-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_logincodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
