# Generated by Django 3.2.5 on 2021-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210713_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='null', upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('front', 'front'), ('producto', 'producto')], max_length=150, null=True),
        ),
    ]
