# Generated by Django 3.2.5 on 2021-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210713_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='image_file',
            field=models.ImageField(default='null', upload_to='blog_image/'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='image_file',
            field=models.ImageField(default='null', upload_to='recipe_image/'),
        ),
    ]
