# Generated by Django 3.2.5 on 2021-07-18 17:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210713_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='null', upload_to=main.models.imageName),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('front', 'front'), ('product', 'product'), ('front_short', 'front_short'), ('main', 'main')], max_length=150, null=True),
        ),
    ]
