# Generated by Django 3.2.6 on 2021-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='puntosVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.IntegerField(blank=True)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('latitud', models.FloatField(null=True)),
                ('longitud', models.FloatField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('creado_el', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'punto de ventas',
            },
        ),
    ]
