# Generated by Django 3.2.6 on 2021-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('front', 'front'), ('product', 'product'), ('front_short', 'front_short'), ('main', 'main'), ('front_mobile', 'front_mobile')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(),
        ),
    ]
