# Generated by Django 3.2.6 on 2022-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_recipe_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='odoo_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
