# Generated by Django 3.2.6 on 2022-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_zoho'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='rut',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
