# Generated by Django 3.2.6 on 2021-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_tradegecko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
