# Generated by Django 3.2.6 on 2021-10-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
